// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAtuFsT5LiMnfqF4D5YY4SmCHb5bhCtr2g',
    appId: '1:1079555606536:web:6168a71180b348914529bd',
    messagingSenderId: '1079555606536',
    projectId: 'time-tracker-flutter-1f323',
    authDomain: 'time-tracker-flutter-1f323.firebaseapp.com',
    storageBucket: 'time-tracker-flutter-1f323.appspot.com',
    measurementId: 'G-B7BSQG75VB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCSW-q_Rqi2PJfPFVMvhs1P9irRvj1WKx0',
    appId: '1:1079555606536:android:baa481dd2f46d93d4529bd',
    messagingSenderId: '1079555606536',
    projectId: 'time-tracker-flutter-1f323',
    storageBucket: 'time-tracker-flutter-1f323.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD-mb2xiZEjJD6Qj1Sw-yAYgUROM7qHQng',
    appId: '1:1079555606536:ios:0612b26768bfa4954529bd',
    messagingSenderId: '1079555606536',
    projectId: 'time-tracker-flutter-1f323',
    storageBucket: 'time-tracker-flutter-1f323.appspot.com',
    androidClientId: '1079555606536-v585t821m9fi793tnb0ir4pd2k2f9ffc.apps.googleusercontent.com',
    iosClientId: '1079555606536-94kaf0a3u73072a9dbohv0m5tmti35e1.apps.googleusercontent.com',
    iosBundleId: 'com.example.timeTracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD-mb2xiZEjJD6Qj1Sw-yAYgUROM7qHQng',
    appId: '1:1079555606536:ios:0612b26768bfa4954529bd',
    messagingSenderId: '1079555606536',
    projectId: 'time-tracker-flutter-1f323',
    storageBucket: 'time-tracker-flutter-1f323.appspot.com',
    androidClientId: '1079555606536-v585t821m9fi793tnb0ir4pd2k2f9ffc.apps.googleusercontent.com',
    iosClientId: '1079555606536-94kaf0a3u73072a9dbohv0m5tmti35e1.apps.googleusercontent.com',
    iosBundleId: 'com.example.timeTracker',
  );
}
